#!/usr/bin/env python

import os
import sys
import fileinput
import re
from datetime import datetime
from contextlib import closing

note_file_path = os.path.expanduser('~/notes.txt')
todo_prefix = '-'
done_prefix = '*'

#TODO: handle empty and malformed lines in the file?
#TODO: handle non-existant file?

with open(note_file_path, 'r') as note_file:
    todos = [line for line in note_file.readlines() if line.startswith(todo_prefix)]

if len(sys.argv) == 1:
    for idx, line in enumerate(todos):
        print '{} {}'.format(idx, line),

    print 'Which note are you done with?'
elif len(sys.argv) == 2 and sys.argv[1].isdigit():
    digit = int(sys.argv[1])
    with closing(fileinput.FileInput(note_file_path, inplace=True)) as note_file:
        for line in note_file:
            if todos[digit] == line:
                print re.sub(r'^' + todo_prefix, done_prefix, line),
            else:
                print line,

    print 'Done!'
else:
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    note = ' '.join(sys.argv[1:])
    with open(note_file_path, 'a') as note_file:
        note_file.write('{} {} {}\n'.format(todo_prefix, now, note))

    print 'Noted!'
