" Generated by vim-plug
" Fri Dec 23 02:15:34 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '1e398202b9a63fcd91808a3205d3422b79435fa0'
silent! let g:plugs['coc.nvim'].commit = '28feeffa7daa1cfe0373c00b1d58f9d293691a1e'
silent! let g:plugs['fzf'].commit = '8e283f512acb74faef6f1760927e1ef4da1b5263'
silent! let g:plugs['fzf.vim'].commit = '7434543270d76b4d9448956112b16cc78a3d165b'
silent! let g:plugs['matchit.zip'].commit = '60067c225e3656d9c72fe42c9173777d2d8ff35b'
silent! let g:plugs['tagbar'].commit = 'af3ce7c3cec81f2852bdb0a0651d2485fcd01214'
silent! let g:plugs['vim-airline'].commit = '6a4c82c950cc10388117e927b89a72a557e5944c'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-css-color'].commit = '1c4b78f5512980227ca747e76f1f6c904f2eb3dc'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-fontzoom'].commit = 'b411334b6abaaf07380521d8446a59553fc7f57f'
silent! let g:plugs['vim-fugitive'].commit = '5b0b138483de17a8fd8dfcec0b491782c8fbf102'
silent! let g:plugs['vim-hocon'].commit = 'bb8fb14e00f8fc1eec27dd39dcc605aac43328a3'
silent! let g:plugs['vim-markdown'].commit = 'feadbc81e27f277187c29957ec6114f1e95f2162'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-tmux-navigator'].commit = '41ea9d23b814014c8d8daf8b44fa0cd827a0e5f4'
silent! let g:plugs['vimux'].commit = '616fcb4799674a7a809b14ca2dc155bb6ba25788'

PlugUpdate!

