" Generated by vim-plug
" Wed May 12 14:01:41 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'bee8eccb421968d1f2628c15e9f2bfcc3d0418aa'
silent! let g:plugs['coc.nvim'].commit = '6cc7432fa00d8a7351cee54f7b800e992057315a'
silent! let g:plugs['fzf'].commit = '4cd621e877cb3a8e44b12ba3a7ce58709862922f'
silent! let g:plugs['fzf.vim'].commit = 'a88311b222eb9f90fa9fa72292e61d15c6767866'
silent! let g:plugs['matchit.zip'].commit = '60067c225e3656d9c72fe42c9173777d2d8ff35b'
silent! let g:plugs['tagbar'].commit = 'f6012cb65da4bda46b0779a36840df36ad01483e'
silent! let g:plugs['vim-airline'].commit = 'ab4962b83866e181b989cb550c527cbfa327942c'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-css-color'].commit = 'cabad5f2a247296145ab4059df98e92cdb3ffe78'
silent! let g:plugs['vim-easymotion'].commit = 'd75d9591e415652b25d9e0a3669355550325263d'
silent! let g:plugs['vim-fontzoom'].commit = 'b411334b6abaaf07380521d8446a59553fc7f57f'
silent! let g:plugs['vim-fugitive'].commit = '0868c30cc08a4cf49b5f43e08412c671b19fa3f0'
silent! let g:plugs['vim-hocon'].commit = 'bb8fb14e00f8fc1eec27dd39dcc605aac43328a3'
silent! let g:plugs['vim-markdown'].commit = '9d87cc19179496db50fb6d902987737c4b522e38'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-tmux-navigator'].commit = '6a1e58c3ca3bc7acca36c90521b3dfae83b2a602'
silent! let g:plugs['vimux'].commit = 'ee0dfae33062419f2c9ef6a202b3ce415adf6e6a'

PlugUpdate!

