" Generated by vim-plug
" Sat Jun 15 13:49:17 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = 'f0ce9ae23d6ce9d0cbabe73bdb738e45accc6f08'
silent! let g:plugs['fzf'].commit = '7fc13c5cfde55ae53c6f87290a80559fcc59bf0f'
silent! let g:plugs['fzf.vim'].commit = '279e1ec068f526e985ee7e3f62a71f083bbe0196'
silent! let g:plugs['matchit.zip'].commit = '60067c225e3656d9c72fe42c9173777d2d8ff35b'
silent! let g:plugs['tagbar'].commit = '0815b5455c792a610d28ff3e7981642c9cf05d62'
silent! let g:plugs['traces.vim'].commit = '9663fcf84de5776bee71b6c816c25ccb6ea11d1a'
silent! let g:plugs['vim-airline'].commit = '16c1638f93f93fad41da8cb6eef2bcd8eed0a57a'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-css-color'].commit = '950e80352b325ff26d3b0faf95b29e301c200f7d'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-fontzoom'].commit = 'b411334b6abaaf07380521d8446a59553fc7f57f'
silent! let g:plugs['vim-fugitive'].commit = '4f59455d2388e113bd510e85b310d15b9228ca0d'
silent! let g:plugs['vim-hocon'].commit = 'bb8fb14e00f8fc1eec27dd39dcc605aac43328a3'
silent! let g:plugs['vim-markdown'].commit = 'f405b47fd8774ecd5e808e6de9c85d9029da251c'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-tmux-navigator'].commit = '5b3c701686fb4e6629c100ed32e827edf8dad01e'
silent! let g:plugs['vimux'].commit = 'fa35410805b82ffabc29e3cb5cdf3ad0b8dc402d'

PlugUpdate!

