" Generated by vim-plug
" Sun Aug 20 17:51:07 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = '9332d2ab1154dedc9dbcd3e1c873886abaf061a6'
silent! let g:plugs['fzf'].commit = 'cf552b5f3b1c52df014904dd82a7885f52f070bc'
silent! let g:plugs['fzf.vim'].commit = '811f34b70b60b4df2997e3ba8cd109e7d06d683b'
silent! let g:plugs['matchit.zip'].commit = '60067c225e3656d9c72fe42c9173777d2d8ff35b'
silent! let g:plugs['tagbar'].commit = '402e3e117fc7b47e43dbb87c51064daae3bc3bf3'
silent! let g:plugs['traces.vim'].commit = '9663fcf84de5776bee71b6c816c25ccb6ea11d1a'
silent! let g:plugs['vim-airline'].commit = 'e6bb8427dc2d2dc3583ed1bf5ff6a9682c854d32'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-css-color'].commit = '6cc65734bc7105d9677ca54e2255fcbc953ba6bf'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-fontzoom'].commit = 'b411334b6abaaf07380521d8446a59553fc7f57f'
silent! let g:plugs['vim-fugitive'].commit = 'b3b838d690f315a503ec4af8c634bdff3b200aaf'
silent! let g:plugs['vim-hocon'].commit = 'bb8fb14e00f8fc1eec27dd39dcc605aac43328a3'
silent! let g:plugs['vim-markdown'].commit = 'f2b82b7884a3d8bde0c5de7793b27e07030eb2bc'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-tmux-navigator'].commit = 'addb64a772cb4a3ae1f1363583012b2cada2cd66'
silent! let g:plugs['vimux'].commit = '616fcb4799674a7a809b14ca2dc155bb6ba25788'

PlugUpdate!

