addSbtPlugin("io.spray"             % "sbt-revolver"            % "0.7.2")
addSbtPlugin("net.virtual-void"     % "sbt-dependency-graph"    % "0.7.5")
addSbtPlugin("com.eed3si9n"         % "sbt-assembly"            % "0.14.0")
addSbtPlugin("com.timushev.sbt"     % "sbt-updates"             % "0.1.9")
//addSbtPlugin("com.typesafe.sbt"     % "sbt-git"                 % "0.8.5")
